### ISSUE TITLE
Reorganize and fix URLs to resolve content

### ISSUE THREAD

**Issue by lcomet** [mobilityDCAT-AP/controlled-vocabularies#1]
Consider the draft and published versions only.
Once the identifier "mobilitydcat-ap" under w3id is available:

1. Fix the URL of the controlled vocabularies from https://mobilitydcat-ap.github.io/controlled-vocabularies/(...) to https://w3id.org/mobilitydcat-ap/(...) in the Readme file.
2. Fix the URL in the Readme file, currently redirecting to https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/index.html
3. After fixing the URLs, check the redirecting.

**Comment by marioscrock** [comment]
@lcomet can we close this issue?
