### ISSUE TITLE
[mobility-theme] Missing values from Delegated Regulation 2024/490 (MMTIS-Regulation)

### ISSUE THREAD

**Issue by peterlubrich** [mobilityDCAT-AP/controlled-vocabularies#10]
The current value list for "Mobility Theme" was created at the time of the "old" MMTIS Regulation 2017/1926.
However, in the "new" MMTIS Regulation 2024/490, some data categories were added, so some values are missing in our list.
These data categories are:

- Parameters needed to calculate fuel consumption of conventional and alternative fuels
- Park & Drive stops
- Existence of assistance services (such as existence of on-site assistance)
- Estimated travel times by day type and time-band by transport mode/combination of transport modes
- Historic travel and traffic data on delays – for scheduled transport and transport on demand
- Observed data on delays and passing time – for scheduled transport
- Observed data on cancellations – for scheduled transport:
- Occupancy information of the vehicle – for scheduled transport and transport on demand

To-Do:

- Check how to name / organise these data categories in our value list.
- Update controlled vocabulary.

**Comment by marioscrock** [comment]
As commented in #10, I suggest having a dedicated meeting to revise all the issues associated with the `mobility-theme` controlled vocabulary. Once the updates are agreed upon, I will create a new version of the controlled vocabulary accordingly.

**Comment by marioscrock** [comment]
Moved discussion to #23
