### ISSUE TITLE
[update-frequency] Missing values in EU Authority List

### ISSUE THREAD

**Issue by peterlubrich** [mobilityDCAT-AP/controlled-vocabularies#11]
We link this to a Controlled Vocab from the EU Authority List. Because this vocab is missing some values that we need, we added another proprietary vocab. Both vocabs together provide the entire list of possible values.

SEMIC states that this is possible, but it is better to contact the team of the EU Authority List, and ask them to upgrade their vocab, so we don't need a proprietary vocab.

-> We need to contact the EU Authority List, but only after our v1.0 publication.

**Comment by marioscrock** [comment]
@peterlubrich could you please confirm the next steps (when the new Frequency Authority Table is published):
- we will "deprecate" our controlled vocabulary (i.e., `https://w3id.org/mobilitydcat-ap/update-frequency`). It should still be hosted for backward compatibility but I will add a note that is deprecated.
- update the recommendation in the new version of the mobilitydcat-ap spec to clarify that only the Frequency Authority Table should be used (I would remove the references to the controlled vocabulary `update-frequency` and put a note in the changelog clarifying what we did and the fact that the `update-frequency` vocabulary is now deprecated)

**Comment by marioscrock** [comment]
The new version of the EU vocabulary was published with requested values at http://publications.europa.eu/resource/authority/frequency

**Comment by marioscrock** [comment]
TODO 
- [ ] @marioscrock "deprecate" our controlled vocabulary (i.e., `https://w3id.org/mobilitydcat-ap/update-frequency`). It should still be hosted for backward compatibility but I will add a note that is deprecated. Moreover, I will add `skos:exactMatch` notations to reference that the "old values" have the same meaning of the ones now available the Frequency Authority Table.
- [ ] @peterlubrich update the recommendation in the new version of the mobilitydcat-ap spec to clarify that only the Frequency Authority Table should be used (I would remove the references to the controlled vocabulary `update-frequency` and put a note in the changelog clarifying what we did and the fact that the `update-frequency` vocabulary is now deprecated)

**Comment by peterlubrich** [comment]
Removed link to our controlled vocabulary under draft for [v1.0.1](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/index.html#changes-since-20240424)
@marioscrock : please deprecate our controlled vocabulary & close this issue

**Comment by marioscrock** [comment]
Thanks @peterlubrich, I will do it as soon as v1.1.0 of the spec is released

**Comment by peterlubrich** [comment]
Meeting 05.12.2024:
Decision procedure for the proposed change:

_[Frequency:](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/#vocab-update-frequency) The [original controlled vocabulary "update frequency" by mobilityDCAT-AP ](https://w3id.org/mobilitydcat-ap/update-frequency)is deprecated, as it is not needed any longer. Only the EU Authority Table "Frequency" is now used, as it now contains all necessary values. DECISION POINT: YES / NO_

**Decision result: no opposition, change to be announced in v1.1.0**

**Comment by peterlubrich** [comment]
@marioscrock :
Can you please label this [website](https://mobilitydcat-ap.github.io/controlled-vocabularies/update-frequency/latest/index.html#/) as DEPRECATED? It is not promoted anymore, but still online, and I want to prevent that people use it, thanks!

**Comment by marioscrock** [comment]
I wrote on the website, in the repo and in the RDF serialisation that it is deprecated but we should not remove it from the web. It is still referenced from old versions of mobilityDCAT-AP, so it is important to keep it online for anyone finding such an IRI online.
