### ISSUE TITLE
[mobility-theme] Alignment of subcategories for "public transport scheduled transport" and "public transport non-scheduled transport"

### ISSUE THREAD

**Issue by BWitsch** [mobilityDCAT-AP/controlled-vocabularies#14]
Public transport non-scheduled transport has the category "Accesibility information for vehicles" but "public transport scheduled transport" not.
Environmental standards for vehicles is in both main categories listed
We need a concept for categories wich are valid for both like: Hours of operation, Vehicle details,...

**Comment by peterlubrich** [comment]
Proposal:

- Add sub-category "Accesibility information for vehicles" for "public transport scheduled transport"
- Consider for an update of the Controlled Vocab [Mobility Theme](https://mobilitydcat-ap.github.io/controlled-vocabularies/mobility-theme/latest/index.html#/).
- Find a solution for identical sub-categories that are used for multiple categories (example:

**Comment by marioscrock** [comment]
Moved discussion to #23
