### ISSUE TITLE
[update-frequency] Values "unknown", "other", "on occurence/irregularly" and "continously" missing 

### ISSUE THREAD

**Issue by BWitsch** [mobilityDCAT-AP/controlled-vocabularies#15]

**Comment by marioscrock** [comment]
> contains "update frequency" as a category

cf. reply from @peterlubrich in #17 

> values "unknown", "other", "on occurence/irregularly" and "continously" missing

As commented by @peterlubrich, the missing values are available in the EU Authority Table "Frequency", which will become the single vocabulary recommended for usage in the next release of mobilityDCAT-AP.

@BWitsch please close this issue if you don't have additional questions on this topic.
