### ISSUE TITLE
[mobility-theme] Data category "Bike-Parking Locations" should be under main category "Cycling Network Data"

### ISSUE THREAD

**Issue by BWitsch** [mobilityDCAT-AP/controlled-vocabularies#16]

**Comment by marioscrock** [comment]
We may also mention "Bike-Parking Locations" as sub-category of both [Cycle network data](https://mobilitydcat-ap.github.io/controlled-vocabularies/mobility-theme/latest/index.html#/cycle-network-data) and [Parking, service and rest area information](https://mobilitydcat-ap.github.io/controlled-vocabularies/mobility-theme/latest/index.html#/parking-service-and-rest-area-information).

**Comment by marioscrock** [comment]
Moved discussion to #23
