### ISSUE TITLE
[transport-mode] Controlled vocabulary "transport mode" contains "transport mode" as type

### ISSUE THREAD

**Issue by BWitsch** [mobilityDCAT-AP/controlled-vocabularies#17]
![grafik](https://github.com/user-attachments/assets/53721596-87fc-4b1c-b430-42d736c3525f)

**Comment by marioscrock** [comment]
Thank you @BWitsch for the question and @peterlubrich for the detailed answer. Exactly, the `skos:ConceptScheme` "Transport Mode" is part of the RDF serialization of the controlled vocabulary but only the `skos:Concept` associated should be considered as values.

@BWitsch please close this issue if you don't have additional questions on this topic.
