### ISSUE TITLE
[mobility-theme] Cycle Network Data - Data Content Categories - Name convention

### ISSUE THREAD

**Issue by BWitsch** [mobilityDCAT-AP/controlled-vocabularies#20]
Dear all,
while implementing the mobility dcat theme I figured out a smal detail:
In the data content category "Pedestrian network data" all Data categories starts with pedestrian... e.g. "Pedestrian network geometry"
In the data content category "Cycle network data" no Data categories contains cycle in the beginning e.g. "Network geometry and lane character"

Shouldn't they have the same naming convention?
Even to prevent miss understaning for cycle data.

KR Benjamin

**Comment by marioscrock** [comment]
Hi @BWitsch, thank you for opening this issue! I agree with this suggestion, and I believe that also other terms (e.g., related to Road Data) may benefit from a review of the naming conventions. This can be done as part of the next release introducing also the mapping to DR discussed in #8 

- [ ] Review with domain experts the naming conventions for the mobility-theme (@peterlubrich)
- [ ] Add deprecation/relatedBy notes for changing IRIs

**Comment by marioscrock** [comment]
Moved discussion to #23
