### ISSUE TITLE
[conditions-for-access-and-usage] Add values with "combinations" of access/usage options

### ISSUE THREAD

**Issue by peterlubrich** [mobilityDCAT-AP/controlled-vocabularies#22]
This issue is a result of another issue at the mobilityDCAT-AP repository [#27](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/issues/27).
This means will keep the existing values:

- Contractual arrangement
- Fee required
- Free of charge
- Licence provided
- Other
- Royalty-free

(so existing adopters can still use the Vocab)

...but add the following "combinations":

- Licence provided, free of charge
- Licence provided, fee required
- Contractual arrangement, free of charge
- Contractual arrangement, fee required

(these four additions were already defined as values for element "Contract or Licence" in the former Coordinated Metadata Catalogue, and allow for "combinations" of the existing values.)

To do:

- [x] await formal decision to realise the option defined in issue [#27](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/issues/27)
- [x] Add the four new values to RDF vocabulary
- [x] Publish new 1.1. version of vocabulary

**Comment by peterlubrich** [comment]
@marioscrock Please add the four values to the controlled vocab:

- Licence provided, free of charge
- Licence provided, fee required
- Contractual arrangement, free of charge
- Contractual arrangement, fee required

**Comment by marioscrock** [comment]
Values added and version 1.1.0 published 👍
