### ISSUE TITLE
Discuss about visibility-status controlled vocabulary

### ISSUE THREAD

**Issue by marioscrock** [mobilityDCAT-AP/controlled-vocabularies#3]
keep, review or remove?

**Comment by peterlubrich** [comment]
There is a parallel issue in on the property with the same name "visibility status":
https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/issues/12
See under point 1. 
Depending on the outcome, let's decide on this vocab.

**Comment by marioscrock** [comment]
@peterlubrich Following the discussion I removed the visibility-status vocab for this version
