### ISSUE TITLE
Mobility Theme: Typo for Car-sharing Stations

### ISSUE THREAD

**Issue by marioscrock** [mobilityDCAT-AP/controlled-vocabularies#5]
Currently, there are "Car-sharing Locations and stations" and "Car-sharing Stations". The second one is probably a typo and should be "Car-hiring Stations" that is missing.

**Comment by peterlubrich** [comment]
Please:
1. produce a new version 1.0.1. of the affected Controlled Vocab, including the repairing of the wrong values.
2. clarify how the evolution of mobilityDCAT-AP (1.0.0 -> 1.0.1) and the evolution of the Controlled Vocab (1.0.0 -> 1.0.1)  correlates. So far, I think, both is independent.  We can keep it this way, so users have the freedom to deploy ANY version of mobilityDCAT-AP in combination with ANY version of our Controlled Vocabs. I will make an own GitHub issue, so we decide together on this approach. However,  we need to make sure that previous versions of the Vocabs are also online: is this possible with our Vocab repository?

**Comment by marioscrock** [comment]
1. New version 1.0.1 generated fixing the controlled vocab. The changelog and hierarchical description were manually edited.
2. I agree on keeping the spec and controlled vocab versions independent. Yes, all the previous versions will stay online and the newest version will have a link to the previous one.
