### ISSUE TITLE
Separate versioning and maintenance of the vocabularies

### ISSUE THREAD

**Issue by burespe1** [mobilityDCAT-AP/controlled-vocabularies#6]
The issue at hand is that all vocabularies are currently housed in a single repository. This arrangement reduces transparency, particularly when one vocabulary is updated without corresponding updates to the others. The use of GitHub version tags and release tags is also problematic, as they refer to the entire repository rather than individual vocabularies.

Could you please clarify the rationale behind consolidating all vocabularies into a single repository? Additionally, could you weigh in on whether, considering the balance between maintenance and clarity, it would be beneficial to separate individual vocabularies into their own repositories?

**Comment by marioscrock** [comment]
@burespe1 thank you for your comment! Each vocabulary is assigned its own URI using the [w3id](https://w3id.org/) redirection mechanism for publication. This guarantees the unique identification of each vocabulary, the correct management of versioning and the decoupling of the URI from the hosting solution chosen. For this reason, we can at any time decide to split the content of this repository into different ones (e.g., one for each vocabulary).

We decided to use a single repository for the hosting to facilitate the "findability" of the repository from a maintenance perspective. Indeed, for an end user, the vocabularies are published as separate entities (each one with its URI) and this aspect affects only issue management.

However, considering your comment, I will add two improvements: 
- a table in the README to keep track of the current version of each vocabulary
- a template for issues to force the user to declare the target controlled vocabulary
