### ISSUE TITLE
[mobility-theme] Referencing to data categories from EC Delegated Regulations

### ISSUE THREAD

**Issue by peterlubrich** [mobilityDCAT-AP/controlled-vocabularies#8]
We plan to reference all “categories” & “sub categories” (from our Controlled Vocabulary [Mobility Theme (mobilitydcat-ap.github.io)](https://mobilitydcat-ap.github.io/controlled-vocabularies/mobility-theme/latest/index.html#/) to the corresponding data categories from EC Regulations.

Reason: see Wikipage, [section 3.2](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/wiki/Chapter-3:-Extra-explanations-on-specific-Metadata-elements#2-reference-of-a-data-set-to-ec-delegated-regulations-and-other-legislature).
 
There will be an additional entry under each “category” & “sub category” in our Controlled Vocabulary.
We will use the property “dcatap:applicableLegislation” for that addition.
This will be done in a future version of the Controlled Vocabulary.
 
By the way: there was already a referencing to the EC Regulations for the Coordinated Metadata Catalogue:
https://www.its-platform.eu/wp-content/uploads/ITS-Platform/AchievementsDocuments/NAP/EU%20EIP_Coord.%20Metadata%20Catalogue_Annex%20I_v2.0_191115.xlsx

We need volunteers to re-do such referencing in the Controlled Vocabulary "Mobility Theme".

**Comment by peterlubrich** [comment]
I propose to add the Excel table for "mobilityTheme" as follows:

![image](https://github.com/mobilityDCAT-AP/controlled-vocabularies/assets/64193173/c121c8e9-31da-41c6-b325-cf00e906a87b)

New column "dcatap:applicableLegislation" - reusing definition and range from the same [property ](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/index.html#dataset-applicable-legislation ) in mobilityDCAT-AP 1.0.1. It links to the relevant Delegated Regulation via the ELI identifier syste,

New column "mobilitydcatap:delegatedRegulationCategory" - this is a new property which we would define in a future release of mobilityDCAT-AP. It denotes exactly the relevant data categories under the relevant EC Delegated Regulations. 

@marioscrock : please let me know if I can proceed this way

**Comment by marioscrock** [comment]
> I propose to expand the Excel table for "mobilityTheme" as follows: [...]

Yes, this is what I had in mind. I will then work out how to ensure that the association in the column is also automatically serialised in RDF.

> * New column "dcatap:applicableLegislation" - reusing definition and range from the same [property ](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/index.html#dataset-applicable-legislation) in mobilityDCAT-AP 1.0.1. It links to the relevant Delegated Regulation via the ELI identifier.

Yes, I agree on the property chosen and the usage of ELI identifiers. You can use the comma to list multiple ELI identifiers for the same category if needed.

> * New column "mobilitydcatap:delegatedRegulationCategory" - this is a new property which we would define in a future release of mobilityDCAT-AP. It denotes exactly the relevant data categories under the relevant EC Delegated Regulations.

I would like to discuss this one a little bit further. Do we expect a 1:1 match between our vocab and the delegated regulation categories? In this case, this can be seen as an "alternative label" of the same concept in the controlled vocabulary. 
I am not sure if it makes sense to add to mobilitydcatap: two properties to specify "two types" of categories (mobilityTheme and delegatedRegulation Category). I would prefer to keep this association in the controlled vocabulary to reduce the "burden" on the user filling out the metadata fields. 
Finally, I am not convinced of having a property (mobilitydcatap:delegatedRegulationCategory) that requires "complex string" values. From the example provided, it seems that also the values in the last column could be represented hierarchically, e.g., 1 -> a -> ii. If this property is needed, we should either define these as alternative labels of the concepts already defined in our controlled vocabulary (thus already having a IRI) or define new identifiers (IRI) for these categories. An alternative option may be to keep this info only in the Excel as "provenance information" but without serialising it in RDF.

**Comment by marioscrock** [comment]
@peterlubrich if it is 0..n the idea of using alternative labels is valid, we can add as many alternative labels as we want. If we have also the case that a single Del.Reg. Category corresponds to multiple Mobility Theme it is still "technically feasible" but I would say less "logically consistent".

**Comment by peterlubrich** [comment]
> I propose to expand the Excel table for "mobilityTheme" as follows:
> 
> ![image](https://private-user-images.githubusercontent.com/64193173/342804856-5ed07660-aaf6-44e3-984a-6b3a51acbc8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NDE3NjQsIm5iZiI6MTcxOTg0MTQ2NCwicGF0aCI6Ii82NDE5MzE3My8zNDI4MDQ4NTYtNWVkMDc2NjAtYWFmNi00NGUzLTk4NGEtNmIzYTUxYWNiYzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDEzNDQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzNzUyZGMxYWZjNTJjZmM4ZDI0YzQ0ZDMxYjZkZmYwZTBiNmI5Y2ZlNzRhNzNiZTMwZjI4ZWFiYTUzMTA1ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ZeGYk_GvIe1KuHGCzjrwV1SOnQwQIq__1-1KaPyojc)
> 
> * New column "dcatap:applicableLegislation" - reusing definition and range from the same [property ](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/index.html#dataset-applicable-legislation) in mobilityDCAT-AP 1.0.1. It links to the relevant Delegated Regulation via the ELI identifier.
> * New column "mobilitydcatap:delegatedRegulationCategory" - this is a new property which we would define in a future release of mobilityDCAT-AP. It denotes exactly the relevant data categories under the relevant EC Delegated Regulations.
> 
> @marioscrock : please let me know if I can proceed this way

I completed the expanded Excel file, as proposed above:
[mobility-theme_added_applicableLegislation_240628.xlsx](https://github.com/user-attachments/files/16053849/mobility-theme_added_applicableLegislation_240628.xlsx)

There are now additional columns:

- F,G:  dcatap:applicableLegislation (value 1,2)
- H,I,J,K: mobilitydcatap:delegatedRegulationCategory  (value 1,2,3,4)

The reason for the multiple values is the 0...n cardinality, as discussed above.

To do:
We need to sort out how to do the RDF representations correctly. @marioscrock had some suggestions above.
The expanded Excel file serves as a starting point for a future revision of the Controlled Vocabulary.

**Comment by peterlubrich** [comment]
Status 27.8.24:
To do:
1. Check if mapping proposal by Peter is correct : domain experts needed @EdNDW @CRVH : send out Teams meeting to SWG4.4 to discuss mapping
2. Apply in update of Controlled Vocab of "Mobility Theme" @Mario

**Comment by peterlubrich** [comment]
Email sent by Peter 29.08.24:

Dear Ed, Christian, Jonas, Mario,

One of the open actions from our last meeting is:
Mapping of our controlled vocab “mobilityTheme” vs. the various EC Delegated Regulations.
Next, I am compiling some support information.

General goal:
Add new information to existing controlled vocab “mobilityTheme”, linking each value from this controlled vocab to :
(a)	one (or more) Delegated Regulations
(b)	one (or more) data categories from these Delegated Regulations

Baseline documents:
Current version of “mobilityTheme”: https://mobilitydcat-ap.github.io/controlled-vocabularies/mobility-theme/latest/index.html#/
Related GitHub issue: https://github.com/mobilityDCAT-AP/controlled-vocabularies/issues/8
Previous mapping exercises (including Coord. Metadata Catalogue from 2019; SE mapping from 2023; DK mapping from 2024): [see NAPCORE Sharepoint](https://rupprechtconsultde.sharepoint.com/:f:/r/sites/NAPCOREallpartners/Shared%20Documents/SubWG4.4/Work%20Items/Work%20Item%204.4.3.2%20Hosting%20of%20%E2%80%9Ccontrolled%20vocabularies%E2%80%9D/Mapping%20mobilityTheme%20vs.%20EC%20Delegated%20Regulations/Input%20files?csf=1&web=1&e=XwpNxf)
New mapping proposal by Peter: [see NAPCORE Sharepoint](https://rupprechtconsultde.sharepoint.com/:x:/r/sites/NAPCOREallpartners/Shared%20Documents/SubWG4.4/Work%20Items/Work%20Item%204.4.3.2%20Hosting%20of%20%E2%80%9Ccontrolled%20vocabularies%E2%80%9D/Mapping%20mobilityTheme%20vs.%20EC%20Delegated%20Regulations/mobility-theme_added_applicableLegislation_240628.xlsx?d=w7ec162e1490742eea79f677e29ce9159&csf=1&web=1&e=PHe99P) 

What is to do:
1.	Check if mapping proposal by Peter is correct, compare with previous mappings 
2.	Apply mapping information as update of Controlled Vocab of "Mobility Theme" (Mario will add additional properties as RDF codes)

Working proposal:
Ed, Christian please:
•	Propose an online meeting, send out to entire SWG 4.4 group
•	Moderate meeting, work for consensus


@Christian: what is your GitHub user name?
@Jonas: I am adding you to this action, as you had sent me some comment about using the “mobility theme” during 2023.

Thanks everyone!
Peter

**Comment by peterlubrich** [comment]
Update:
Ed Ooms and Christian von Huth (DK) have provided a mapping on the level:
_1 Value from Vocab "Mobility Theme " -> Reference to 1..n Delegated Regulations_

I have verified this mapping with our own mapping attempts (see above "New mapping proposal by Peter"). 

Result:
- Some refinements done in our mapping table
- Produced a new "source excel table" for Vocab "Mobility Theme", see on [Sharepoint](https://rupprechtconsultde.sharepoint.com/:x:/r/sites/NAPCOREallpartners/Shared%20Documents/SubWG4.4/Work%20Items/Work%20Item%204.4.3.2%20Hosting%20of%20%E2%80%9Ccontrolled%20vocabularies%E2%80%9D/Mapping%20mobilityTheme%20vs.%20EC%20Delegated%20Regulations/[mobility-theme_added_applicableLegislation_241113.xlsx](https://rupprechtconsultde.sharepoint.com/:x:/r/sites/NAPCOREallpartners/Shared%20Documents/SubWG4.4/Work%20Items/Work%20Item%204.4.3.2%20Hosting%20of%20%E2%80%9Ccontrolled%20vocabularies%E2%80%9D/Mapping%20mobilityTheme%20vs.%20EC%20Delegated%20Regulations/mobility-theme_added_applicableLegislation_241113.xlsx?d=w7bcf88b2315043a19f563cced5f072ab&csf=1&web=1&e=Tp7w5L)?d=w7bcf88b2315043a19f563cced5f072ab&csf=1&web=1&e=Tp7w5L)

**To do now:**

@marioscrock , please:
1. produce a new RDF vocabulary based on the new "source excel table"
1.1. insert a `dcatap:applicableLegislation` property for each entry in columns F,G,H,
1.2 if "n/a" is noted, do nothing here!
2. Deprecate the current versionof "Mobility Theme"
3.  Publish a new version 1.1 of  of "Mobility Theme"

**To do later:**

The above actions ignore the more granular referencing to "mobilitydcatap:delegatedRegulationCategory", as proposed by me above. This needs more analyses / discussions, and will be considered for another update of "Mobility Theme".

**Comment by marioscrock** [comment]
Thank you @peterlubrich! I edited the file on Sharepoint to keep all the values as a comma-separated list in a single column.

TODO
- [ ] The property is currently not visible in the "human-readable" documentation, find a way to describe the mapping in the vocabulary docs
- [ ] finalise other issues related to mobility-theme before releasing 1.1.0 of the vocab

**Comment by peterlubrich** [comment]
Meeting 05.12.2024:
Decision procedure for the proposed change:

_[Mobility Theme:](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/#vocab-mobility-theme) Added references to EC Delegated Regulations via additional dcatap:applicableLegislation properties for all values used in this vocabulary. This allows for an automated tagging of EC Regulations to individual datasets.  DECISION POINT: YES / NO_

**Decision result: no opposition, change to be announced in v1.1.0**

**Comment by marioscrock** [comment]
@peterlubrich EC Delegated Regulations added to v1.1 of the controlled-vocabulary, now available online at https://w3id.org/mobilitydcat-ap/mobility-theme
